name: Render Auto-Deploy Trigger

on:
  push:
    branches: [ main ]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Notify
        run: echo "🟢 Code pushed to main. Render will build and deploy using Dockerfiles."
